project:
  type: book
  preview:
    browser: false

book:
  title: "Project DMP User Guide"
  subtitle: "Creating a PARC Project DMP in the Data Stewardship Wizard"
  page-footer:
    center:
      - text: "License: CC-BY 4.0"
        href: https://creativecommons.org/licenses/by/4.0/
  author:
    - name: Indrani Mahapatra
      id: im
      orcid: 0000-0002-6396-0848
      affiliation:
        - id: uob
          name: University of Birmingham, UK
          ror: https://ror.org/03angcq70
    - name: Iseult Lynch
      id: il
      orcid: 0000-0003-4250-4584
      affiliation:
        - ref: uob
    - name: Fred van de Brug
      id: fb
      orcid: 0000-0002-3462-0967
      affiliation:
        - name: RIS, TNO, NL
          ror: https://ror.org/01bnjb948
    - name: Rob Stierum
      id: rs
      orcid: 0000-0002-4409-1974
      affiliation:
        - name: RAPID, TNO, NL
          ror: https://ror.org/01bnjb948
    - name: Katarína Řiháčková
      id: kr
      orcid: 0000-0003-0222-801X
      affiliation:
        - name: RECETOX, Masaryk University, CZ
          ror: https://ror.org/032hzqh22
    - name: Stijn Baken
      id: sb
      orcid: 0000-0002-2483-3969
      affiliation:
        - name: VITO, BE
          ror: https://ror.org/04gq0w522
    - name: Dario Bijker
      id: db
      orcid: 0000-0002-0319-6542
      affiliation:
        - ref: lacdr
    - name: Gerhard Burger
      id: gab
      orcid: 0000-0003-1062-5576
      affiliation:
        - id: lacdr
          name: LACDR, Leiden University, NL
          ror: https://ror.org/027bh9e22
  license: "CC BY"
  chapters:
    - index.qmd
    - intro.qmd
    - dsw.qmd
    - create_project.qmd
    - misc.qmd
  appendices:
    - appendix.qmd
    - faq.qmd
    - references.qmd
  # downloads: [pdf]
  site-url: https://eu-parc.github.io/project-dmp-guide
  repo-url: https://github.com/eu-parc/project-dmp-guide
  repo-branch: main
  repo-actions: [edit, issue]
  search: true
  sidebar:
    tools:
      - icon: envelope
        href: mailto:wp7-dmp-troubleshooters@googlegroups.com
    # footer: sidebar_footer.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    logo: images/PARC.svg
    grid:
      body-width: 900px
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: header.tex

include-in-header:
- text: |
    <meta name="robots" content="noindex, nofollow">

