---
callout-appearance: default
callout-icon: false
format:
  html:
    toc-depth: 4
---

## FAQ

::: {.callout-warning icon="true"}
## This FAQ is a work in progress
Additional questions/tips will be added over time.
:::

::: {.callout-important icon="true"}
## I need help!
Please contact the WP7 DMP Team by clicking the {{< bi envelope >}} icon on the top-left (below the PARC logo), or by clicking {{< var people.dmpteam >}}.
:::

### General {.unnumbered}

::: {.callout-note }
## What is the difference between the questions in grey, red, and green?
The questions in red/green are mandatory, the questions in grey  are optional (in this phase). Some questions will become mandatory at a later DMP phase. Optional questions are often used to clarify responses for mandatory questions with a fixed response format and/or will enrich the DMP. 
:::
::: {.callout-note }
## What does the “Metrics” tab show?
Some of the responses in the DMP are used by the WP7 team to capture whether the responses in the DMP are sufficient to ensure that FAIR data is planned to be achieved. For example, the data being reported in PARC data reporting templates would give a FAIRness score. Note that the DMP is just a plan, and it is only when the actions described in the DMP are actually implemented by the data-generating partners in the project that the data is actually FAIR.  Implementation of the DMP is verified by the project managers. The metrics cover the Findability of Data, the Accessibility of Data etc.
:::
### DMP Questions {.unnumbered}

#### I. Administrative information {.unnumbered} 

::: {.callout-note }
## My affiliation doesn't show in the dropdown?
Sometimes it helps to type the full name of the institution. If it still doesn't show up, check if your affiliation is registered at https://ror.org/, if not, just provide the URL to your affiliation homepage. 
:::

::: {.callout-note }
## We don’t have a link to the project proposal, what should we do?
You can link to the project proposal in the ANSES Sharepoint. In addition, WP7 will create persistent links to a FAIR summary of the project proposal which they will insert at a later stage
:::

::: {.callout-note }
## What should we answer for the question “To execute the DMP, is additional specialist expertise required?”
The answer to the question should be “yes” as FAIR data and Data Management needs training and expertise, even if it’s just in using the PARC metadata templates or uploading the metadata to the PARC CRA Hub (as examples). If you have hired people who also contribute to data harmonisation for use in computational models or in the SSbD Toolbox for example, this will be addressed here.
:::

::: {.callout-note }
## What is the function of the “Add” button?
For example, if more than one Database has been agreed for use, each should be added and described. Similarly, for different types of data (e.g., images, omics data of different types) the “Add” button can be used to add each data type and then answer the Question for each one.
:::

#### II. Re-using data {.unnumbered}
::: {.callout-note }
## If we don’t have URLs or PIDs (e.g., doi) for datasets reused, what should we do?
If the data was curated from scientific journals or grey literature, into an MS Excel or such, this should be deposited in Zenodo to generate a DOI.  This can be closed / embargoed if needed until the paper is published. If data isn’t submitted in Zenodo, add as much detail as possible in the box provided for adding doi (non-URL input is accepted).
:::

#### III. Creating and collecting data {.unnumbered} 
::: {.callout-note }
## If we don’t have URLs or PIDs (e.g., doi) for datasets reused, what should we do?
If the data was curated from scientific journals or grey literature, into an MS Excel or such, this should be deposited in Zenodo to generate a DOI.  This can be closed / embargoed if needed until the paper is published. If data isn’t submitted in Zenodo, add as much detail as possible in the box provided for adding doi (non-URL input is accepted).
:::
::: {.callout-note }
## How should we answer the questions related to storing of physical samples?
Various project partners will practice different ways to preserve physical samples and with various aims. Add all practices adopted to preserve physical samples for the long- and thereby supporting its potential reuse in the box provided. 
:::
#### IV. Processing data {.unnumbered}
#### V. Interpreting data {.unnumbered}
#### VI. Preserving data {.unnumbered}
#### VII. Giving access to data {.unnumbered}

